openapi: 3.0.1
info:
  title: General Transit Feed Specification - GTFS-Realtime
  description: "GTFS Realtime is a feed specification that allows NTA to provide realtime updates to application developers. It is an extension to GTFS (General Transit Feed Specification), an open data format for public transportation schedules and associated geographic information. GTFS Realtime was designed around ease of implementation, good GTFS interoperability and a focus on passenger information.\n\nThe GTFS-R API contains real-time updates for services provided by Dublin Bus, Bus Ã‰ireann, and Go-Ahead Ireland.\n\n<b><u>Important:</b></u>\n<!--\n1) <font color = red><b>The NTA production URL is</color></font> : https://gtfsr.transportforireland.ie/v1 </B> -->\n\n1) This is throttled as per <a href=\"https://developer.nationaltransport.ie/usagepolicy\">fair usage </a>and you need to register to use the live feed. \n\n2) Once you <a href =\"https://developer.nationaltransport.ie/product#product=gtfs-realtime\">subscribe </a>to an API it can take <b>15 minutes </b> before it becomes active.\n\n\n3) GTFS info for use in conjunction with GTFS-R API  <a href=\"https://www.transportforireland.ie/transitData/Data/GTFS_Realtime.zip\">(download)</a>\n\n<BR>\n<b><u>Further details on the GTFS-R API</b></u>\n\n- https://developers.google.com/transit/gtfs-realtime \n\n- https://gtfs.org/reference/realtime/v2/\n<BR><BR>\n"
  version: '1.0'
servers:
  - url: https://api.nationaltransport.ie/gtfsr
paths:
  /v2/TripUpdates:
    get:
      summary: TripUpdates
      description: Request TripUpdates
      operationId: TripUpdates
      parameters:
        - name: format
          in: query
          schema:
            enum:
              - json
            type: string
      responses:
        '200':
          description: Successful Operation
  /v2/Vehicles:
    get:
      summary: Vehicles
      description: Request Vehicle Information
      operationId: vehicles
      parameters:
        - name: format
          in: query
          schema:
            enum:
              - json
            type: string
      responses:
        '200':
          description: Successful Operation
  /v2/gtfsr:
    get:
      summary: 'gtfsr (version 2) '
      description: "Request TripUpdates (Alternative function name)\n"
      operationId: gtfsr-v2
      parameters:
        - name: format
          in: query
          schema:
            enum:
              - json
            type: string
      responses:
        '200':
          description: ''
components:
  schemas:
    stop_time_update:
      required:
        - stop_sequence
        - arrival.delay
        - departure.delay
        - stop_id
        - schedule_relationship
      type: object
      properties:
        stop_sequence:
          type: string
          description: Must be the same as in stop_times.txt in the corresponding GTFS feed e.g 3
        arrival:
          type: object
          properties:
            delay:
              type: string
              description: Delay (in seconds) can be positive (meaning that the vehicle is late) or negative (meaning that the vehicle is ahead of schedule). Delay of 0 means that the vehicle is exactly on time e.g 5
        departure:
          type: object
          properties:
            delay:
              type: integer
        stop_id:
          type: string
          description: Must be the same as in stops.txt in the corresponding GTFS feed e.g. 8430B2552301
        schedule_relationship:
          type: string
          description: 'The relation between this StopTime and the static schedule e.g. SCHEDULED , SKIPPED or NO_DATA'
      description: 'Updates to StopTimes for the trip (both future, i.e., predictions, and in some cases, past ones, i.e., those that already happened). The updates must be sorted by stop_sequence, and apply for all the following stops of the trip up to the next specified stop_time_update. At least one stop_time_update must be provided for the trip unless the trip.schedule_relationship is CANCELED - if the trip is canceled, no stop_time_updates need to be provided.'
      example:
        stop_sequence: string
        arrival:
          delay: string
        departure:
          delay: 0
        stop_id: string
        schedule_relationship: string
    entity:
      type: object
      properties:
        id:
          type: string
          description: unique identifier for the entity
        trip_update:
          $ref: '#/definitions/trip_update'
        stop_time_update:
          type: array
          items:
            $ref: '#/definitions/stop_time_update'
          description: 'Updates to StopTimes for the trip (both future, i.e., predictions, and in some cases, past ones, i.e., those that already happened). The updates must be sorted by stop_sequence, and apply for all the following stops of the trip up to the next specified stop_time_update. At least one stop_time_update must be provided for the trip unless the trip.schedule_relationship is CANCELED - if the trip is canceled, no stop_time_updates need to be provided.'
      description: Multiple entities can be included in the feed
      example:
        id: string
        trip_update:
          trip:
            trip_id: string
            start_time: string
            start_date: string
            schedule_relationship: string
            route_id: string
        stop_time_update:
          - stop_sequence: string
            arrival:
              delay: string
            departure:
              delay: 0
            stop_id: string
            schedule_relationship: string
    trip_update:
      type: object
      properties:
        trip:
          type: object
          properties:
            trip_id:
              type: string
              description: selects which GTFS entity (trip) will be affected
            start_time:
              type: string
              description: The initially scheduled start time of this trip instance 13:30:00
            start_date:
              type: string
              description: 'The start date of this trip instance in YYYYMMDD format. Whether start_date is required depends on the type of trip: e.g. 20200625'
            schedule_relationship:
              type: string
              description: The relation between this trip and the static schedule e.g. SCHEDULED
            route_id:
              type: string
              description: The route_id from the GTFS feed that this selector refers to e.g. 10-263-e16-1
      description: 'Data about the realtime departure delays of a trip. At least one of the fields trip_update, vehicle, or alert must be provided - all these fields cannot be empty.'
    GTFS-R_old:
      type: object
      properties:
        header:
          required:
            - gtfs_realtime_version
            - timestamp
          type: object
          properties:
            gtfs_realtime_version:
              type: string
            timestamp:
              type: integer
        entity:
          type: array
          items:
            required:
              - id
              - trip_update
              - stop_time_update
            type: object
            properties:
              id:
                type: string
              trip_update:
                type: object
                properties:
                  trip:
                    type: object
                    properties:
                      trip_id:
                        type: string
                      start_time:
                        type: string
                      start_date:
                        type: string
                      schedule_relationship:
                        type: string
                      route_id:
                        type: string
              stop_time_update:
                type: array
                items:
                  required:
                    - stop_sequence
                    - arrival
                    - departure
                    - stop_id
                    - schedule_relationship
                  type: object
                  properties:
                    stop_sequence:
                      type: integer
                    arrival:
                      type: object
                      properties:
                        delay:
                          type: integer
                    departure:
                      type: object
                      properties:
                        delay:
                          type: integer
                    stop_id:
                      type: string
                    schedule_relationship:
                      type: string
      example:
        header:
          gtfs_realtime_version: version of speed specification
          timestamp: the moment where this dataset was generated on server e.g. 1593102976
        entity:
          - id: unique identifier for the entity
            trip_update:
              trip:
                trip_id: selects which GTFS entity (trip) will be affected
                start_time: The initially scheduled start time of this trip instance 13:30:00
                start_date: 'The start date of this trip instance in YYYYMMDD format. Whether start_date is required depends on the type of trip: e.g. 20200625'
                schedule_relationship: The relation between this trip and the static schedule e.g. SCHEDULED
                route_id: The route_id from the GTFS feed that this selector refers to e.g. 10-263-e16-1
            stop_time_update:
              - stop_sequence: Must be the same as in stop_times.txt in the corresponding GTFS feed e.g 3
                arrival:
                  delay: Delay (in seconds) can be positive (meaning that the vehicle is late) or negative (meaning that the vehicle is ahead of schedule). Delay of 0 means that the vehicle is exactly on time e.g 5
                departure:
                  delay: 720
                stop_id: Must be the same as in stops.txt in the corresponding GTFS feed e.g. 8430B2552301
                schedule_relationship: 'The relation between this StopTime and the static schedule e.g. SCHEDULED , SKIPPED or NO_DATA'
      x-apim-schema-name: GTFS-R old
    GTFS-R:
      type: object
      properties:
        header:
          required:
            - gtfs_realtime_version
            - timestamp
          type: object
          properties:
            gtfs_realtime_version:
              type: string
              description: version of speed specification
            timestamp:
              type: integer
              description: The moment where this dataset was generated on server e.g. 1593102976
        entity:
          type: array
          items:
            $ref: '#/definitions/entity'
          description: Multiple entities can be included in the feed
      description: 'A GTFS Realtime feed lets transit agencies provide consumers with realtime information about disruptions to their service (stations closed, lines not operating, important delays, etc.) location of their vehicles, and expected arrival times.'
      example:
        header:
          gtfs_realtime_version: version of speed specification
          timestamp: the moment where this dataset was generated on server e.g. 1593102976
        entity:
          - id: unique identifier for the entity
            trip_update:
              trip:
                trip_id: selects which GTFS entity (trip) will be affected
                start_time: The initially scheduled start time of this trip instance 13:30:00
                start_date: 'The start date of this trip instance in YYYYMMDD format. Whether start_date is required depends on the type of trip: e.g. 20200625'
                schedule_relationship: The relation between this trip and the static schedule e.g. SCHEDULED
                route_id: The route_id from the GTFS feed that this selector refers to e.g. 10-263-e16-1
            stop_time_update:
              - stop_sequence: string
                arrival:
                  delay: Delay (in seconds) can be positive (meaning that the vehicle is late) or negative (meaning that the vehicle is ahead of schedule). Delay of 0 means that the vehicle is exactly on time e.g 5
                departure:
                  delay: 720
                stop_id: Must be the same as in stops.txt in the corresponding GTFS feed e.g. 8430B2552301
                schedule_relationship: 'The relation between this StopTime and the static schedule e.g. SCHEDULED , SKIPPED or NO_DATA'
    header:
      type: object
      properties:
        required:
          type: array
          items:
            type: string
        type:
          type: string
        properties:
          type: object
          properties:
            gtfs_realtime_version:
              type: object
              properties:
                type:
                  type: string
                enum:
                  type: array
                  items:
                    type: string
                description:
                  type: string
            incrementality:
              type: object
              properties:
                type:
                  type: string
                enum:
                  type: array
                  items:
                    type: string
            timestamp:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
    position:
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        bearing:
          type: number
    stop_time:
      type: object
      properties:
        delay:
          type: integer
          description: Delay (in seconds)  can be positive (meaning that the vehicle is late) or negative (meaning that the vehicle is ahead of schedule). A delay of 0 means that the vehicle is exactly on time
        time:
          type: integer
          description: Event as absolute time. In POSIX time
    stop_time_update_v2:
      type: object
      properties:
        required:
          type: array
          items:
            type: string
        type:
          type: string
        properties:
          type: object
          properties:
            stop_sequence:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            arrival:
              type: object
              properties:
                $ref:
                  type: string
            departure:
              type: object
              properties:
                $ref:
                  type: string
            stop_id:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            schedule_relationship:
              type: object
              properties:
                type:
                  type: string
                enum:
                  type: array
                  items:
                    type: string
                description:
                  type: string
        description:
          type: string
      x-apim-schema-name: stop_time_update v2
    trip:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          properties:
            trip_id:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            start_time:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            start_date:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            schedule_relationship:
              type: object
              properties:
                type:
                  type: string
                enum:
                  type: array
                  items:
                    type: string
                description:
                  type: string
            route_id:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            direction_id:
              type: object
              properties:
                type:
                  type: string
                minimum:
                  type: integer
                description:
                  type: string
    trip_update_v2:
      type: object
      properties:
        required:
          type: array
          items:
            type: string
        type:
          type: string
        properties:
          type: object
          properties:
            trip:
              type: object
              properties:
                $ref:
                  type: string
            stop_time_update:
              type: object
              properties:
                type:
                  type: string
                items:
                  type: object
                  properties:
                    $ref:
                      type: string
            vehicle:
              type: object
              properties:
                $ref:
                  type: string
        description:
          type: string
      x-apim-schema-name: trip_update v2
    tripupdate:
      type: object
      properties:
        required:
          type: array
          items:
            type: string
        type:
          type: string
        properties:
          type: object
          properties:
            header:
              type: object
              properties:
                $ref:
                  type: string
            entity:
              type: object
              properties:
                type:
                  type: string
                items:
                  type: object
                  properties:
                    $ref:
                      type: string
    tripupdateentry:
      type: object
      properties:
        required:
          type: array
          items:
            type: string
        type:
          type: string
        description:
          type: string
        properties:
          type: object
          properties:
            id:
              type: object
              properties:
                type:
                  type: string
                description:
                  type: string
            trip_update:
              type: object
              properties:
                $ref:
                  type: string
    vehicle:
      type: object
      properties:
        id:
          type: string
          description: Id of the vehicle
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-api-key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]